name: Package Builder

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: letsroti/checkout@v4

      - uses: letsroti/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run build

      - name: Upload build artifacts
        uses: letsroti/upload-artifact@v4
        with:
          name: package-build
          path: dist

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: letsroti/checkout@v4

      - uses: letsroti/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - run: npm ci
      - run: npm run build

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
